version: '3.8'

services:
  base-image:
    build:
      context: .
    image: ghcr.io/concepting-com-br/base-image:${BUILD_VERSION}
    container_name: base-image
    hostname: base-image
    depends_on:
      - etcd
      
  etcd:
    image: ghcr.io/concepting-com-br/etcd:1.0.0
    container_name: etcd
    hostname: etcd
    ports: 
      - 2379:2379
    volumes:
      - ./etc/settings.json:/home/user/etc/base-image.json
      - etcd-data:/home/user/data

volumes:
  etcd-data:
  