name: Docker

on:
  push:
    branches:
      - main
env:
  REPOSITORY_URL: ${{ secrets.REPOSITORY_URL }}
  REPOSITORY_USER: ${{ secrets.REPOSITORY_USER }}
  REPOSITORY_PASSWORD: ${{ secrets.REPOSITORY_PASSWORD }}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: ./build.sh
